# Jupyter Notebooks and Running Code in Sequence

### Overview
Jupyter notebooks are a great resource to run code sequentially, especially for
machine learning models. Instead of having to retrain your model each time you
run code, jupyter-notebooks allow for you to write code in a segmented progress
and break apart steps. For more information, check out documentation at
https://docs.jupyter.org/en/latest/ .

Try out this short primer. The goal of this small notebook is to give you some
idea regarding how you can use notebooks to run code-blocks.

In [6]:
# An example of a Jupyter notebook. You can run this notebook by clicking on
# the "Run" button above! You can also click "Shift" + "Enter" to run the code
# you're currently on. Pressing it multiple times will run multiple code blocks
# in succession.

print("Hello, world!")

Hello, world!


#### **IMPORTANT!** Make sure that you've selected the specific environment that you set up in the previous step.

If you are using VSCode, remember to “Select Interpreter” (Cmd + Shift + P) and select the previous installed environment. Also, make sure to change the kernel for the jupyter-notebook file in the upper-righthand corner of the notebook and select the specific environment.

Potential Errors:
- Check that you have activated the environment before starting your jupyter-notebook. You can activate the environment with “conda activate [env-name]” and deactivate with “conda deactivate”.
- Check to see if you are using a conda environment in your jupyter-notebook. Create a code block by pressing the “+” symbol, type in “conda”, and run the block.
    - If conda is installed, go back to the terminal and run “conda install [package name]” on packages that you cannot use. 
    - If conda is not installed, make sure to select your kernel as ‘ipykernel’ or your env name. If you are using ‘ipykernel’ or your env name does not exist, go back to the terminal and run the following:
        - conda install jupyter
        - conda install nb_conda
        - conda install ipykernel
        - python -m ipykernel install --user --name [whatever name you want here]
    - Close jupyter-notebook and reopen. When running the jupyter notebook, make sure to set the kernel as your environment name.

### BACK TO THE PRIMER: 

We can also store variables that are used between blocks. This allows for local
variables to be used in blocks that they weren't declared in! Be very careful to
run blocks in order so that you don't run into an error like `NameError: name '???' is not defined`.

In [7]:
# Declaring a variable here!
x = 10

In [9]:
print(f'The number is {x}!')

The number is 10!


Now let's try out some imports from our environment. Make sure to follow the above
instructions about running code from packages installed in your environment if you haven't 
already. 

One such thing we will try out is the `numpy` package. This library is very useful
because it allows for a wide range of data manipulation techniques. For more details,
see the documentation and possibilities [here](https://numpy.org/doc/). 

In [11]:
# If this code block doesn't pass, try some of the debugging tips in the block
# above titled "IMPORTANT". These provide some common issues regarding environments
# and their respective dependency installations.

import numpy as np

In [13]:
# Testing out that numpy imports work!

identityMatrix = np.identity(5)
print(f'Here is a 5x5 identity matrix: \n {identityMatrix}')

Here is a 5x5 identity matrix: 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### Imports from Other Files
While it's useful to be able to run code sequentially so that it's visually presentable
in a jupyter-notebook, it might be inconvenient to write all the relevant code here.
Instead, it may be preferable to import functions other related information from code
files that you've written. In this repository, we've provided you with a code file
titled `sample.py`. This file contains a method titled `isOdd` which returns `true`
when the inputted number is odd and `false` when it is not. Consider the following
syntax.

In [15]:
import sample

isOneOdd = "Yes!" if sample.isOdd(1) else "No!"

print(isOneOdd)

Yes!


The provided code above is simple but is also included for the sake of pedagogy. 
If you choose to use jupyter-notebooks when creating your project, the complexity and
scope is ultimately up to you.

This concludes the jupyter-notebook primer section of the machine learning 
starter pack. Now feel free to move on to the [PyTorch guide](3-pytorch.ipynb) which
will provide a more contextual guide on the PyTorch library!